-- Code Generated by Sidekick is for learning and experimentation purposes only.
{{
config(
    materialized='incremental',
    incremental_strategy='delete+insert',
    unique_key="sk_fct_revenue_record",
    tags=["SC_fct"]
)
}}

with source as (

    select
        revenue_system,
        revenue_record_id,
        revenue_date,
        product_id,
        revenue_amount,
        revenue_currency,
        revenue_channel,
        revenue_status,
        revenue_audit_id,
        revenue_audit_time as src_audit_time

    from {{ source("sap_erp","aufk_hist") }}

    {% if is_incremental() %}
        changes (information => append_only) at(timestamp => '{{ dbt_xom_package.get_incremental_ts(this) }}'::timestamp_tz)
        where
            metadata$action = 'INSERT'
            and src_audit_time > '{{ dbt_xom_package.get_incremental_ts(this)}}'::timestamp_tz
            and revenue_system in ('P4')
        qualify 1 row_number() over(
            partition by revenue_system, revenue_record_id order by "header_timestamp" desc
        )
    {% else %}
        where
            is_valid_flag = true and revenue_system in ('P4')
    {% endif %}

),

final as (

    select
        ifnull(
            {{
                dbt_utils.generate_surrogate_key([
                    'src.revenue_system', 'src.revenue_record_id'
                ])
            }}, '-1'
        ) as sk_fct_revenue_record,

        src.revenue_record_id,
        src.product_id,
        src.revenue_date,
        src.revenue_amount,
        src.revenue_currency,
        src.revenue_channel,
        src.revenue_status,
        src.revenue_system as source_system,
        src.revenue_audit_id as audit_id,
        'AUFK_HIST' as stage_source_table,
        src.src_audit_time as source_audit_datetime,
        current_timestamp() as current_audit_datetime

    from source as src

)

select
    sk_fct_revenue_record,
    revenue_record_id,
    product_id,
    revenue_date,
    revenue_amount,
    revenue_currency,
    revenue_channel,
    revenue_status,
    source_system,
    audit_id,
    stage_source_table,
    source_audit_datetime,
    current_audit_datetime

from final
